// Flexar Hub Web — bundled emoji corpus for typeahead (Phase 2.3).
//
// A curated starter set of common Unicode emoji shortcodes used by the
// `:` typeahead in the compose box. This is deliberately small (~120
// entries) — the full Zulip set is huge, and the typeahead's job is to
// surface the popular handful, not to be exhaustive. The shortcodes
// match Zulip's own names where they exist (the server renders `:fire:`
// → 🔥 the same way regardless of what we surface here).
//
// Custom realm emoji are intentionally out of scope: there is no store
// for them in this phase, and threading them through would balloon the
// scope. Document this limitation.
//
// Each entry is `{ shortcode, glyph }`. The shortcode is what gets
// inserted into the textarea (`:smile:` etc.); the glyph is shown
// alongside the shortcode in the typeahead row so the user sees what
// they will get. Sorted alphabetically here to keep diffs readable;
// runtime ordering is computed by `emojiSource`.

export interface EmojiEntry {
  /** The `:foo:` shortcode (without the surrounding colons). */
  shortcode: string;
  /** Display glyph (Unicode emoji) shown next to the shortcode. */
  glyph: string;
}

export const EMOJI_CORPUS: readonly EmojiEntry[] = [
  { shortcode: "100", glyph: "💯" },
  { shortcode: "alarm_clock", glyph: "⏰" },
  { shortcode: "alien", glyph: "👽" },
  { shortcode: "anger", glyph: "💢" },
  { shortcode: "angry", glyph: "😠" },
  { shortcode: "arrow_down", glyph: "⬇️" },
  { shortcode: "arrow_left", glyph: "⬅️" },
  { shortcode: "arrow_right", glyph: "➡️" },
  { shortcode: "arrow_up", glyph: "⬆️" },
  { shortcode: "balloon", glyph: "🎈" },
  { shortcode: "beer", glyph: "🍺" },
  { shortcode: "bell", glyph: "🔔" },
  { shortcode: "bicyclist", glyph: "🚴" },
  { shortcode: "birthday", glyph: "🎂" },
  { shortcode: "blush", glyph: "😊" },
  { shortcode: "bomb", glyph: "💣" },
  { shortcode: "book", glyph: "📖" },
  { shortcode: "bookmark", glyph: "🔖" },
  { shortcode: "boom", glyph: "💥" },
  { shortcode: "bow", glyph: "🙇" },
  { shortcode: "broken_heart", glyph: "💔" },
  { shortcode: "bug", glyph: "🐛" },
  { shortcode: "cake", glyph: "🍰" },
  { shortcode: "calendar", glyph: "📅" },
  { shortcode: "check", glyph: "✅" },
  { shortcode: "checkered_flag", glyph: "🏁" },
  { shortcode: "clap", glyph: "👏" },
  { shortcode: "clock", glyph: "🕐" },
  { shortcode: "coffee", glyph: "☕" },
  { shortcode: "cold_sweat", glyph: "😰" },
  { shortcode: "computer", glyph: "💻" },
  { shortcode: "confetti_ball", glyph: "🎊" },
  { shortcode: "confused", glyph: "😕" },
  { shortcode: "cookie", glyph: "🍪" },
  { shortcode: "cool", glyph: "😎" },
  { shortcode: "cry", glyph: "😢" },
  { shortcode: "dancer", glyph: "💃" },
  { shortcode: "disappointed", glyph: "😞" },
  { shortcode: "dog", glyph: "🐶" },
  { shortcode: "exclamation", glyph: "❗" },
  { shortcode: "eyes", glyph: "👀" },
  { shortcode: "facepalm", glyph: "🤦" },
  { shortcode: "fearful", glyph: "😨" },
  { shortcode: "fire", glyph: "🔥" },
  { shortcode: "flushed", glyph: "😳" },
  { shortcode: "frown", glyph: "🙁" },
  { shortcode: "ghost", glyph: "👻" },
  { shortcode: "gift", glyph: "🎁" },
  { shortcode: "grin", glyph: "😁" },
  { shortcode: "grinning", glyph: "😀" },
  { shortcode: "hammer", glyph: "🔨" },
  { shortcode: "hand", glyph: "✋" },
  { shortcode: "handshake", glyph: "🤝" },
  { shortcode: "headphones", glyph: "🎧" },
  { shortcode: "hear_no_evil", glyph: "🙉" },
  { shortcode: "heart", glyph: "❤️" },
  { shortcode: "heart_eyes", glyph: "😍" },
  { shortcode: "hibiscus", glyph: "🌺" },
  { shortcode: "hot", glyph: "🥵" },
  { shortcode: "hourglass", glyph: "⏳" },
  { shortcode: "hugs", glyph: "🤗" },
  { shortcode: "joy", glyph: "😂" },
  { shortcode: "key", glyph: "🔑" },
  { shortcode: "kiss", glyph: "😘" },
  { shortcode: "laughing", glyph: "😆" },
  { shortcode: "light_bulb", glyph: "💡" },
  { shortcode: "link", glyph: "🔗" },
  { shortcode: "lock", glyph: "🔒" },
  { shortcode: "lol", glyph: "😂" },
  { shortcode: "love_letter", glyph: "💌" },
  { shortcode: "mag", glyph: "🔍" },
  { shortcode: "mailbox", glyph: "📫" },
  { shortcode: "memo", glyph: "📝" },
  { shortcode: "mortar_board", glyph: "🎓" },
  { shortcode: "musical_note", glyph: "🎵" },
  { shortcode: "neutral", glyph: "😐" },
  { shortcode: "no_entry", glyph: "⛔" },
  { shortcode: "notebook", glyph: "📓" },
  { shortcode: "octopus", glyph: "🐙" },
  { shortcode: "ok_hand", glyph: "👌" },
  { shortcode: "open_mouth", glyph: "😮" },
  { shortcode: "package", glyph: "📦" },
  { shortcode: "paperclip", glyph: "📎" },
  { shortcode: "party", glyph: "🥳" },
  { shortcode: "party_popper", glyph: "🎉" },
  { shortcode: "peace", glyph: "✌️" },
  { shortcode: "phone", glyph: "📱" },
  { shortcode: "pin", glyph: "📌" },
  { shortcode: "pizza", glyph: "🍕" },
  { shortcode: "point_down", glyph: "👇" },
  { shortcode: "point_left", glyph: "👈" },
  { shortcode: "point_right", glyph: "👉" },
  { shortcode: "point_up", glyph: "☝️" },
  { shortcode: "poop", glyph: "💩" },
  { shortcode: "pray", glyph: "🙏" },
  { shortcode: "punch", glyph: "👊" },
  { shortcode: "question", glyph: "❓" },
  { shortcode: "rainbow", glyph: "🌈" },
  { shortcode: "raised_hands", glyph: "🙌" },
  { shortcode: "robot", glyph: "🤖" },
  { shortcode: "rocket", glyph: "🚀" },
  { shortcode: "rofl", glyph: "🤣" },
  { shortcode: "rolling_eyes", glyph: "🙄" },
  { shortcode: "rose", glyph: "🌹" },
  { shortcode: "running", glyph: "🏃" },
  { shortcode: "sad", glyph: "😢" },
  { shortcode: "salt", glyph: "🧂" },
  { shortcode: "see_no_evil", glyph: "🙈" },
  { shortcode: "shipit", glyph: "🚢" },
  { shortcode: "shrug", glyph: "🤷" },
  { shortcode: "skull", glyph: "💀" },
  { shortcode: "sleeping", glyph: "😴" },
  { shortcode: "smile", glyph: "😄" },
  { shortcode: "smirk", glyph: "😏" },
  { shortcode: "snowflake", glyph: "❄️" },
  { shortcode: "soccer", glyph: "⚽" },
  { shortcode: "sob", glyph: "😭" },
  { shortcode: "sparkles", glyph: "✨" },
  { shortcode: "speak_no_evil", glyph: "🙊" },
  { shortcode: "speech_balloon", glyph: "💬" },
  { shortcode: "star", glyph: "⭐" },
  { shortcode: "star2", glyph: "🌟" },
  { shortcode: "stop_sign", glyph: "🛑" },
  { shortcode: "sun", glyph: "☀️" },
  { shortcode: "sunglasses", glyph: "😎" },
  { shortcode: "sweat_smile", glyph: "😅" },
  { shortcode: "tada", glyph: "🎉" },
  { shortcode: "thinking", glyph: "🤔" },
  { shortcode: "thumbs_down", glyph: "👎" },
  { shortcode: "thumbs_up", glyph: "👍" },
  { shortcode: "tongue", glyph: "😛" },
  { shortcode: "trophy", glyph: "🏆" },
  { shortcode: "umbrella", glyph: "☂️" },
  { shortcode: "unamused", glyph: "😒" },
  { shortcode: "unicorn", glyph: "🦄" },
  { shortcode: "v", glyph: "✌️" },
  { shortcode: "warning", glyph: "⚠️" },
  { shortcode: "watermelon", glyph: "🍉" },
  { shortcode: "wave", glyph: "👋" },
  { shortcode: "wink", glyph: "😉" },
  { shortcode: "x", glyph: "❌" },
  { shortcode: "yum", glyph: "😋" },
  { shortcode: "zany", glyph: "🤪" },
  { shortcode: "zzz", glyph: "💤" },
];
