#!/bin/bash
# Flexar Zulip deploy script — runs on the server as the `deploy` user.
#
# Usage:
#   ./deploy_zulip.sh <full_image_ref>
# Example:
#   ./deploy_zulip.sh ghcr.io/afedotov89/flexar-zulip-server:abc123
#
# Mirrors the structure of deploy_polymarket.sh, but takes the full image
# reference as a single argument (registry-agnostic — works for ghcr.io,
# cr.yandex, docker.io, whatever).
#
# Required env vars (passed from GitHub Actions via SSH):
#   ZULIP__POSTGRES_PASSWORD, ZULIP__MEMCACHED_PASSWORD,
#   ZULIP__RABBITMQ_PASSWORD, ZULIP__REDIS_PASSWORD,
#   ZULIP__SECRET_KEY, ZULIP_EXTERNAL_HOST, ZULIP_ADMIN_EMAIL
#
# Optional:
#   ZULIP_HTTP_PORT (default 8800)
#   ZULIP_HTTPS_PORT (default 8843)
#   ZULIP_ENV_FILE (default /home/deploy/zulip.env)
#   ZULIP__EMAIL_PASSWORD, SETTING_EMAIL_HOST, SETTING_EMAIL_HOST_USER,
#   SETTING_EMAIL_PORT, SETTING_EMAIL_USE_TLS, SETTING_NOREPLY_EMAIL_ADDRESS,
#   ZULIP_AUTH_BACKENDS, CERTIFICATES, LOADBALANCER_IPS, TRUST_GATEWAY_IP,
#   NGINX_WORKERS, AUTO_BACKUP_ENABLED, COMPOSE_PROJECT_NAME

set -euo pipefail

FULL_IMAGE_NAME="${1:-}"

if [ -z "${FULL_IMAGE_NAME}" ]; then
  echo "ERROR: Usage: $0 <full_image_ref>"
  echo "Example: $0 ghcr.io/afedotov89/flexar-zulip-server:abc123"
  exit 1
fi

# Derive registry host for prune-old-images step at the end.
REGISTRY_HOST="${FULL_IMAGE_NAME%%/*}"
# Strip tag to get repo (everything up to the last `:`).
IMAGE_REPO="${FULL_IMAGE_NAME%:*}"

COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-flexar-zulip}"
DEPLOY_DIR="${DEPLOY_DIR:-/home/${USER}/zulip}"
DEFAULT_ENV_FILE="/home/${USER}/zulip.env"
ENV_FILE_PATH="${ZULIP_ENV_FILE:-${DEFAULT_ENV_FILE}}"

ZULIP_HTTP_PORT="${ZULIP_HTTP_PORT:-8800}"
ZULIP_HTTPS_PORT="${ZULIP_HTTPS_PORT:-8843}"

REQUIRED_VARS=(
  "ZULIP__POSTGRES_PASSWORD"
  "ZULIP__MEMCACHED_PASSWORD"
  "ZULIP__RABBITMQ_PASSWORD"
  "ZULIP__REDIS_PASSWORD"
  "ZULIP__SECRET_KEY"
  "ZULIP_EXTERNAL_HOST"
  "ZULIP_ADMIN_EMAIL"
)

echo "===> Flexar Zulip deploy"
echo "  Image:       ${FULL_IMAGE_NAME}"
echo "  Project:     ${COMPOSE_PROJECT_NAME}"
echo "  Deploy dir:  ${DEPLOY_DIR}"
echo "  Env file:    ${ENV_FILE_PATH}"
echo "  Ports:       ${ZULIP_HTTP_PORT}/${ZULIP_HTTPS_PORT}"

# ------------------------------------------------------------
# Validate required env vars
# ------------------------------------------------------------
for var in "${REQUIRED_VARS[@]}"; do
  if [ -z "${!var:-}" ]; then
    echo "ERROR: required env var ${var} is not set"
    exit 1
  fi
done

# ------------------------------------------------------------
# Pull image from cr.yandex
# ------------------------------------------------------------
echo "===> Pulling image ${FULL_IMAGE_NAME}..."
if ! docker pull "${FULL_IMAGE_NAME}"; then
  echo "ERROR: failed to pull image"
  exit 1
fi

# ------------------------------------------------------------
# Ensure deploy directory exists and is owned by deploy user
# ------------------------------------------------------------
mkdir -p "${DEPLOY_DIR}"

# ------------------------------------------------------------
# Materialize/refresh .env file from env vars (atomic write).
# We rewrite it every deploy so secret rotation just works.
# ------------------------------------------------------------
echo "===> Writing ${ENV_FILE_PATH}..."
TMP_ENV="$(mktemp)"
chmod 600 "${TMP_ENV}"
cat > "${TMP_ENV}" <<EOF
# Auto-generated by deploy_zulip.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ").
# Do not edit by hand — your changes will be overwritten on next deploy.

COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
ZULIP_IMAGE=${FULL_IMAGE_NAME}

ZULIP_HTTP_PORT=${ZULIP_HTTP_PORT}
ZULIP_HTTPS_PORT=${ZULIP_HTTPS_PORT}

ZULIP__POSTGRES_PASSWORD=${ZULIP__POSTGRES_PASSWORD}
ZULIP__MEMCACHED_PASSWORD=${ZULIP__MEMCACHED_PASSWORD}
ZULIP__RABBITMQ_PASSWORD=${ZULIP__RABBITMQ_PASSWORD}
ZULIP__REDIS_PASSWORD=${ZULIP__REDIS_PASSWORD}
ZULIP__SECRET_KEY=${ZULIP__SECRET_KEY}
ZULIP__EMAIL_PASSWORD=${ZULIP__EMAIL_PASSWORD:-}

ZULIP_EXTERNAL_HOST=${ZULIP_EXTERNAL_HOST}
ZULIP_ADMIN_EMAIL=${ZULIP_ADMIN_EMAIL}
SETTING_FAKE_EMAIL_DOMAIN=${SETTING_FAKE_EMAIL_DOMAIN:-flexar.local}

SETTING_EMAIL_HOST=${SETTING_EMAIL_HOST:-}
SETTING_EMAIL_HOST_USER=${SETTING_EMAIL_HOST_USER:-}
SETTING_EMAIL_PORT=${SETTING_EMAIL_PORT:-587}
SETTING_EMAIL_USE_TLS=${SETTING_EMAIL_USE_TLS:-True}
SETTING_NOREPLY_EMAIL_ADDRESS=${SETTING_NOREPLY_EMAIL_ADDRESS:-noreply@flexar.local}

ZULIP_AUTH_BACKENDS=${ZULIP_AUTH_BACKENDS:-EmailAuthBackend}

CERTIFICATES=${CERTIFICATES:-self-signed}
LOADBALANCER_IPS=${LOADBALANCER_IPS:-}
TRUST_GATEWAY_IP=${TRUST_GATEWAY_IP:-false}

NGINX_WORKERS=${NGINX_WORKERS:-2}
AUTO_BACKUP_ENABLED=${AUTO_BACKUP_ENABLED:-false}
EOF
mv "${TMP_ENV}" "${ENV_FILE_PATH}"

# ------------------------------------------------------------
# Refresh docker-compose.yml from the freshly-pulled image — every
# deploy. The image is the source of truth; if we kept the old compose
# file, hostname/port/env changes that landed in the repo would never
# take effect on the server (compose would see no config diff and skip
# recreating sidecars). This bit me on the memcached SASL fix.
# ------------------------------------------------------------
COMPOSE_FILE="${DEPLOY_DIR}/docker-compose.yml"
TMP_COMPOSE="$(mktemp)"
echo "===> Refreshing docker-compose.yml from image..."
if ! docker run --rm --entrypoint cat "${FULL_IMAGE_NAME}" \
    /root/zulip/flexar/deploy/docker-compose.yml > "${TMP_COMPOSE}" 2>/dev/null; then
  echo "ERROR: could not extract docker-compose.yml from image."
  rm -f "${TMP_COMPOSE}"
  exit 1
fi
if [ ! -s "${TMP_COMPOSE}" ]; then
  echo "ERROR: extracted docker-compose.yml is empty."
  rm -f "${TMP_COMPOSE}"
  exit 1
fi
mv "${TMP_COMPOSE}" "${COMPOSE_FILE}"

# ------------------------------------------------------------
# Bring up the stack.
# `docker compose pull` ensures sidecar images (postgres, redis, etc.) are
# fresh too; main `zulip` image is already pulled above.
# `up -d --remove-orphans` recreates only containers whose config changed.
# ------------------------------------------------------------
cd "${DEPLOY_DIR}"
echo "===> docker compose pull (sidecars)..."
docker compose --env-file "${ENV_FILE_PATH}" pull --ignore-pull-failures || true

echo "===> docker compose up -d --remove-orphans..."
docker compose --env-file "${ENV_FILE_PATH}" up -d --remove-orphans

# ------------------------------------------------------------
# Wait for the main zulip container to start.
# ------------------------------------------------------------
MAIN_CONTAINER="${COMPOSE_PROJECT_NAME}-server"
echo "===> Waiting for ${MAIN_CONTAINER} to start..."
MAX_ATTEMPTS=30
for i in $(seq 1 $MAX_ATTEMPTS); do
  if docker ps -f "name=${MAIN_CONTAINER}" -f status=running --format '{{.Names}}' | grep -q "${MAIN_CONTAINER}"; then
    echo "  Container is running."
    break
  fi
  if [ "$i" -eq "$MAX_ATTEMPTS" ]; then
    echo "ERROR: ${MAIN_CONTAINER} did not start in time."
    docker logs "${MAIN_CONTAINER}" --tail 80 2>&1 || true
    exit 1
  fi
  sleep 2
done

# ------------------------------------------------------------
# Health check via curl http://localhost:${ZULIP_HTTP_PORT}/health
# Zulip's first-boot can take several minutes (DB migrations, static
# collection, supervisord coming up). Be patient.
# ------------------------------------------------------------
echo "===> Health-check (this may take 5-10 min on first boot)..."
MAX_RETRIES=60
RETRY_INTERVAL=10
for i in $(seq 1 $MAX_RETRIES); do
  if http_code="$(curl -sS -o /tmp/zulip_health -w '%{http_code}' \
        "http://localhost:${ZULIP_HTTP_PORT}/health" 2>/dev/null)"; then
    if [ "${http_code}" -ge 200 ] && [ "${http_code}" -lt 400 ]; then
      echo "  Health check OK (HTTP ${http_code})."
      break
    fi
    echo "  attempt $i/${MAX_RETRIES}: HTTP ${http_code}, retrying..."
  else
    echo "  attempt $i/${MAX_RETRIES}: curl error, retrying..."
  fi
  if [ "$i" -eq "$MAX_RETRIES" ]; then
    echo "ERROR: health check never passed."
    echo "Last 80 lines of zulip container log:"
    docker logs "${MAIN_CONTAINER}" --tail 80 2>&1 || true
    exit 1
  fi
  sleep "${RETRY_INTERVAL}"
done

# ------------------------------------------------------------
# Show final state
# ------------------------------------------------------------
echo "===> Deploy successful."
docker ps --filter "label=com.docker.compose.project=${COMPOSE_PROJECT_NAME}" \
  --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
echo
echo "Zulip is available at:"
echo "  http://${ZULIP_EXTERNAL_HOST%:*}:${ZULIP_HTTP_PORT}/"
echo "  https://${ZULIP_EXTERNAL_HOST%:*}:${ZULIP_HTTPS_PORT}/ (self-signed cert)"

# ------------------------------------------------------------
# Prune old images of this container to save disk.
# Keep only last 3 tags.
# ------------------------------------------------------------
echo "===> Pruning old image tags..."
docker images "${IMAGE_REPO}" \
  --format "{{.Repository}}:{{.Tag}} {{.CreatedAt}}" \
  | sort -k2,3 -r \
  | tail -n +4 \
  | awk '{print $1}' \
  | while read -r image; do
      echo "  removing ${image}"
      docker rmi "${image}" 2>/dev/null || true
    done

echo "===> Done."
